import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Providers from "./store/providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "myntra-clone",
  description: "Generated by Inayat",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <Header />
          
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
